### ISSUE TITLE
Test runner interferes with tabbing

### ISSUE THREAD

**Issue by AsimAM** [dmtrKovalenko/cypress-real-events#43] opened 2021-04-08 14:26 UTC
When starting a test with `cy.realPress('Tab');` it tabs through the cypress window before tabbing through the webpage.

Tried with:
Chrome 89
Node 12.20.1
cypress 6.8.0
cypress-real-events 1.3.0
yarn

**Comment by dmtrKovalenko** [comment] 2021-04-08 14:38
You need to firstly focus internal window. Basically 

```
cy.window().focus()
```

We actually need to think about doing this automatically but need to make sure that it won't affect users test scenario

**Comment by AsimAM** [comment] 2021-04-08 15:33
Yeah it would be great, if you could look into it being done automatically. Let me know if you require assistance.

**Comment by dmtrKovalenko** [comment] 2022-02-11 17:31
duplicate of #196

**Closed** 2022-02-11 17:31 UTC
