### ISSUE TITLE
Styling on hover gone when taking screenshot

### ISSUE THREAD

**Issue by warri93** [dmtrKovalenko/cypress-real-events#288] opened 2022-08-03 13:19 UTC
When using `realHover` to change the colors of a button when hovering, the styling is gone when taking a screenshot.
I tried `cy.screenshot` and `matchImageSnapshot` from `cypress-image-snapshot` but both didn't work.
When looking at the saved video I can clearly see that the styling is applied when hovering the button but it gets lost when the screenshot is taken.

The only thing that works is checking the applied css itself by doing the following: `.should('have.css', 'color', 'rgb(234, 18, 18)')`

cy.get('button').realHover().screenshot('my-screenshot'); // not working
cy.get('button').realHover().matchImageSnapshot('my-screenshot'); // not working

Can someone help with this issue to make it possible to verify the css with a screenshot?

===========================
"cypress": "9.5.0",
"cypress-image-snapshot": "4.0.1",
"cypress-real-events": "1.7.1"
===========================

**Comment by dmtrKovalenko** [comment] 2022-08-03 13:56
Duplicate of #80

**Closed by dmtrKovalenko** 2022-08-03 13:56 UTC
